### ISSUE TITLE
videos for course m102

### ISSUE THREAD

**Issue by sv2402** [przemyslawpluta/mongo-edu#4]
cannot download video for week 4 and week 5 for course M102: MongoDB for DBAs using mongo-edu.  Only the first three weeks videos are showing.

**Comment by istensky** [comment]
Having the same issue now

**Comment by przemyslawpluta** [comment]
I've located the issue ... will push an update at some point today / tomorrow.

**Comment by przemyslawpluta** [comment]
Connected with https://github.com/przemyslawpluta/mongo-edu/issues/43

**Comment by przemyslawpluta** [comment]
https://github.com/przemyslawpluta/mongo-edu/issues/43

**Comment by istensky** [comment]
Error: Command failed: python /usr/local/lib/node_modules/mongo-edu/node_modules/youtube-dl/bin/youtube-dl --dump-json --max-quality=18 https://youtu.be/ 0:42, Dwight mentions that he can get an acknowledgment back from the primary before the write propagates to a secondary.
WARNING: Could not send HEAD request to https://youtu.be/ 0:42, Dwight mentions that he can get an acknowledgment back from the primary before the write propagates to a secondary.: HTTP Error 404: Not Found
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

    at ChildProcess.exithandler (child_process.js:744:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)

**Comment by istensky** [comment]
got it ,thanks.
